Поправить верстку блока .footer (привести в соответствие с макетом)
web-standards-ru/web-standards.ru pull request #138
Opened 2020-10-18 17:57 UTC by PetePearl

Исправление issue https://github.com/web-standards-ru/web-standards.ru/issues/136

2020-10-20 22:42 UTC, pepelsbey requested changes
Я наверное плохо объяснил задачу. Тут получилось улучшение существующей вёрстки до похожести на макет. А я предложил её заменить той, [которая уже готова в демке](https://github.com/pepelsbey/playground/blob/master/31/src/styles/blocks/footer.css). Там не только готовый код, но и принципы, которые хотелось бы распространить по всему коду.

2020-10-21 14:03 UTC, Holiden commented
> Я наверное плохо объяснил задачу. Тут получилось улучшение существующей вёрстки до похожести на макет. А я предложил её заменить той, [которая уже готова в демке](https://github.com/pepelsbey/playground/blob/master/31/src/styles/blocks/footer.css). Там не только готовый код, но и принципы, которые хотелось бы распространить по всему коду.

Раз уж тут зашёл разговор о принципах, я хотел бы уточнить по поводу медиазапросов. Начинаем писать так, как у тебя в демке или остаёмся на старом варианте?

2021-01-18 02:08 UTC, higimo commented
@Holiden если речь о `<` и прочих сравнениях, то да, на это даже есть [соответствующая задача](https://github.com/web-standards-ru/web-standards.ru/issues/160).

2021-01-18 02:09 UTC, higimo commented
@PetePearl сможете ли вы добить ПР?

2021-04-06 20:49 UTC, pepelsbey commented
Пока прикрою, но можно будет вернуться.

2021-04-06 20:49 UTC, closed without merging