Перевод статьи Focus management and inert с CSS tricks
web-standards-ru/web-standards.ru pull request #140
Opened 2020-10-19 16:23 UTC by summertime-fms

2020-10-19 18:20 UTC, pepelsbey commented
Переименовал папку и сконвертировал HTML-код статьи в полный маркдаун, включая код и ссылки с помощью [Turndown](https://domchristie.github.io/turndown/).

2020-10-19 18:27 UTC, pepelsbey commented
Во, теперь все тесты в порядке. Можно продолжать :)

2020-10-20 11:30 UTC, summertime-fms commented
В силу нехватки опыта (пока что) некоторые понятия, как мне кажется, можно перевести красивее. Оставил в комментариях пометки.

2020-10-20 11:43 UTC, pepelsbey commented
Перевод переехал в файл `focus-and-inert/index.md`, файл `focus management and inert/index.md` нужно удалить.

2020-10-21 13:59 UTC, Holiden commented on src/articles/focus-and-inert/index.md
> +- любой элемент с установленным `[tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)` (о нём чуть позже).
@pepelsbey почему-то выше в бектики обернул только теги, а тут всю ссылку целиком?)

2020-10-21 17:27 UTC, pepelsbey commented on src/articles/focus-and-inert/index.md
> +- любой элемент с установленным `[tabindex](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)` (о нём чуть позже).
Не доделал :)

2020-10-22 11:12 UTC, pepelsbey commented on src/people/mikhail-danyushin/index.md
> +url: TODO
@summertime-fms сюда можно добавить ссылку

2020-10-22 12:29 UTC, Holiden commented on src/articles/focus-and-inert/index.md
> +preview: ''
Превью бы написать.

2020-10-22 12:31 UTC, pepelsbey commented on src/articles/focus-and-inert/index.md
> +preview: ''
Это последний шаг, надо сначала зафиналить

2020-10-22 12:35 UTC, summertime-fms commented on src/articles/focus-and-inert/index.md
> +preview: ''
А кто обычно пишет превью? Я бы мог попробовать

2020-10-22 19:23 UTC, pepelsbey commented on src/articles/focus-and-inert/index.md
> +preview: ''
Ревью, это что-то вроде тизера к статье. Чаще собирается из первого или несколькольких первых абзацев. Его имеет смысл писать перед публикацией, когда эти абзацы уже закончены.

2020-10-23 08:15 UTC, MeFoDy submitted a review, later dismissed

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Нет необходимости устанавливать `tabindex` интерактивным элементам, которые могут получать фокус с клавиатуры (такие, как, например, `<button>`). Кроме того, вам не нужно прописывать `tabindex` неинт
```suggestion
Нет необходимости устанавливать `tabindex` интерактивным элементам, которые могут получать фокус с клавиатуры (например, `<button>`). Кроме того, вам не нужно прописывать `tabindex` неинтерактивным элементам для возможности их прочтения вспомогательными устройствами (на самом деле, отсутствие `role` и доступного имени является ошибкой WCAG). Это может повлечь [нежелательный пользовательский опыт](https://adrianroselli.com/2019/02/uncanny-a11y.html#Tabindex) использования вспомогательных устройств — у которых попросту есть свои собственные способы чтения контента.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Атрибут `tabindex="-1"` используется для создания доступных интерактивных виджетов посредством JS. Прописав `tabindex="-1"` вы сделаете элемент фокусируемым для JS, а также по клику или тачу, но недо
```suggestion
Атрибут `tabindex="-1"` используется для создания доступных интерактивных виджетов посредством JS. Прописав `tabindex="-1"`, вы сделаете элемент фокусируемым для JS, а также по клику или тапу, но недоступным через клавишу Tab.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Это антипаттерн. Установив положительное значение `tabindex` вы переопределите ожидемый порядок элементов для фокуса через Tab и запутаете пользователя. Сделать так один раз — уже плохо, несколько —
```suggestion
Это антипаттерн. Установив положительное значение `tabindex`, вы переопределите ожидаемый порядок элементов для фокуса через Tab и запутаете пользователя. Сделать так один раз — уже плохо, несколько — полный кошмар. Серьезно, не надо так.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +- Вы перемещаетесь исключительно с помощью клавиатуры и в случае закрытия модального окна можете потеряться среди страницы в попытках к нему вернуться.
```suggestion
- Вы перемещаетесь исключительно с помощью клавиатуры и в случае закрытия модального окна можете потеряться внутри страницы в попытках к нему вернуться.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +5. Слушать события, сигнализирующие об уходе с выделенной области (сохрание, отмена, нажатие Esc и т. д.)
```suggestion
5. Слушать события, сигнализирующие об уходе с выделенной области (сохранение, отмена, нажатие Esc и т. д.)
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +6. Уйти с захваченной области
Где-то в списке точки стоят, где-то нет. Давайте все списки к одному стилю приведём и везде проставим точки.

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +[Скринридеры обладают режимом взаимодействия](https://tink.uk/understanding-screen-reader-interaction-modes/), который позволяет им проходить по странице виртуальным курсором. А ещё виртуальный курсо
Вижу здесь Ё. Давайте тоже на странице её использование сделаем однообразным: либо используем, либо нет, либо там, где без точечек над Е слово не понятно без контекста.

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +При управлении фокусом может потребоваться ограничить возможность обнаружения содержимого виртуальным курсором. В нашем примере с модальным окном это значит предотвратить пользователя от случайного в
```suggestion
При управлении фокусом может потребоваться ограничить возможность обнаружения содержимого виртуальным курсором. В нашем примере с модальным окном это значит предотвратить случайный выход пользователя за рамки окна при чтении контента.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +[Атрибут `inert`](https://whatpr.org/html/4288/interaction.html#the-inert-attribute) — [глобальный атрибут в HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes), позволяющий ле
```suggestion
[Атрибут `inert`](https://whatpr.org/html/4288/interaction.html#the-inert-attribute) — [глобальный атрибут в HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes), позволяющий легко убирать и восстанавливать видимость интерактивных элементов, а также их возможность получать состояние фокуса. Вот пример:
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +            <p>The changes you have made will be lost if you do not save them.<p>
Может, и тут переведём текст интерфейса?

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +**Помните:** Событие закрытия модального окна может быть вызванно не только нажатием соотетствующих кнопок, но и нажатием на Esc. А еще некоторые модальные окна могут быть закрыты по клику на оверлей
```suggestion
**Помните:** событие закрытия модального окна может быть вызвано не только нажатием соответствующих кнопок, но и нажатием Esc. А еще некоторые модальные окна могут быть закрыты по клику на оверлей.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Все последние версии [Edge, Chrome, and Opera поддерживают `inert`](https://caniuse.com/#feat=mdn-api_htmlelement_inert) если [включены экспериментальные функции веб-платформ](https://css-irl.info/ho
```suggestion
Все последние версии [Edge, Chrome и Opera поддерживают `inert`](https://caniuse.com/#feat=mdn-api_htmlelement_inert), если [включены экспериментальные функции веб-платформ](https://css-irl.info/how-to-enable-experimental-web-platform-features/). Firefox будет поддерживать [в скором времени](https://bugzilla.mozilla.org/show_bug.cgi?id=1655722)! Единственное исключение — Safari. Как мобильный, так и десктопный.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Вдобавок, хочется обратить внимание на [запись в ридми полифила](https://github.com/WICG/inert#performance-and-gotchas):
```suggestion
Вдобавок хочется обратить внимание на [пометку в README полифила](https://github.com/WICG/inert#performance-and-gotchas):
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +> Полифил обойдется вам дорого с точки зрения производительности в отличие от нативного `inert`, т. к. он требует изрядное количество перемещений по DOM.
```suggestion
> Полифил обойдется вам дорого с точки зрения производительности в отличие от нативного `inert`, т. к. он требует изрядного количества перемещений по DOM.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Перемещение по DOM подразумевает что JavaSсript в полифиле требует высокой вычислительной мощности и, следовательно, в конечном итоге замедлит пользователя.
```suggestion
Перемещение по DOM подразумевает, что JavaSсript в полифиле требует высокой вычислительной мощности и, следовательно, в конечном итоге замедлит пользователя.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Для устройств с низким энергопотреблением таких как [бюджетные Android смартфоны и устаревшие ноутбуки](https://www.pewresearch.org/fact-tank/2019/05/07/digital-divide-persists-even-as-lower-income-a
```suggestion
Для устройств с низким энергопотреблением, таких как [бюджетные Android смартфоны и устаревшие ноутбуки](https://www.pewresearch.org/fact-tank/2019/05/07/digital-divide-persists-even-as-lower-income-americans-make-gains-in-tech-adoption/ft\_17-03-21\_low-incometech_smartphone/), а также тех, что выполняют сложные задачи (например, запуск нескольких приложений сразу), это может привести к зависанию или сбоям. Нативная браузерная поддержка делает такие процессы менее затратными в этом плане, так как у браузера есть доступ ко всем частям DOM, в отличие от JS.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +К сожалению, Apple держит в тайне, когда воявится поддержка этого атрибута. Поэтому поддержка `inert` — все еще открытый вопрос.
```suggestion
К сожалению, Apple держит в тайне, когда появится поддержка этого атрибута. Поэтому поддержка `inert` — все еще открытый вопрос.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Одно из предложений Igalia — это [добавление поддержки `inert` в WebKit](https://www.igalia.com/open-prioritization/#inertwebkit). Если вы искали возможность принять участие в улучшении доступности в
```suggestion
Одно из предложений Igalia — это [добавление поддержки `inert` в WebKit](https://www.igalia.com/open-prioritization/#inertwebkit). Если вы искали возможность принять участие в улучшении доступности веба, но не знали с чего начать, я могу вам [ее предоставить](https://opencollective.com/html-inert-in-webkit-safari). $5, $10, $25 — совсем необязательно жертвовать большие суммы, даже маленький вклад ценен.
```

2020-10-23 08:15 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Такие техники, как `inert` являются примером одной из самых сильных сторон веба: [способность кодифицировать неожиданное поведение](https://www.w3.org/TR/html-design-principles/#pave-the-cowpaths) в 
```suggestion
Такие техники, как `inert`, являются примером одной из самых сильных сторон веба: [способности кодифицировать неожиданное поведение](https://www.w3.org/TR/html-design-principles/#pave-the-cowpaths) в нечто простое и эффективное.
```

2020-10-23 08:52 UTC, pepelsbey commented
@summertime-fms вы своим последним коммитом откатили мои предыдущие обширные правки. Надо всё-таки апаться, когда вместе работаешь.

2020-10-23 08:56 UTC, pepelsbey commented
Откатил до своего коммита.

2020-10-23 08:59 UTC, pepelsbey commented on src/articles/focus-and-inert/index.md
> +            <p>The changes you have made will be lost if you do not save them.<p>
К сожалению, он не переведён на видео, так что я бы оставил

2020-10-23 09:01 UTC, pepelsbey commented on src/articles/focus-and-inert/index.md
> +Одно из предложений Igalia — это [добавление поддержки `inert` в WebKit](https://www.igalia.com/open-prioritization/#inertwebkit). Если вы искали возможность принять участие в улучшении доступности в
$5, $10, $25 — эта запись принята в англоязычной типографике. Располагать символ валюты в зависимости от валюты — это плохой подход. Ты же не будешь писать ₽100?

2020-10-23 09:03 UTC, pepelsbey commented on src/articles/focus-and-inert/index.md
> +[Скринридеры обладают режимом взаимодействия](https://tink.uk/understanding-screen-reader-interaction-modes/), который позволяет им проходить по странице виртуальным курсором. А ещё виртуальный курсо
Политика с «Ё» на сайте простая: буква используется всегда.

2020-10-23 09:07 UTC, MeFoDy commented on src/articles/focus-and-inert/index.md
> +Одно из предложений Igalia — это [добавление поддержки `inert` в WebKit](https://www.igalia.com/open-prioritization/#inertwebkit). Если вы искали возможность принять участие в улучшении доступности в
Я тут полностью согласен с Бирманом: https://ilyabirman.ru/meanwhile/all/dollar-sign/
Мы у себя в одном крупном проекте используем именно международные обозначения валют. Рубли по международным правилам пишутся после количества.

2020-10-23 09:11 UTC, pepelsbey commented on src/articles/focus-and-inert/index.md
> +Одно из предложений Igalia — это [добавление поддержки `inert` в WebKit](https://www.igalia.com/open-prioritization/#inertwebkit). Если вы искали возможность принять участие в улучшении доступности в
И всё же, у нас принято так: 100 €, 100 $, 100 ₽

2020-10-23 10:43 UTC, TatianaFokina requested changes

2020-10-23 10:43 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +- [Ссылки](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a), с заполненным атрибутом `href`
```suggestion
- [Ссылки](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) с заполненным атрибутом `href`,
```
Запятая перед предлогом "с" тут не требуется, а вот добавить запятую после первого пункта списка было бы неплохо.

2020-10-23 10:43 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +- [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) и [`<textarea>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea), с сопутствующим им [`<label>`](htt
```suggestion
- [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) и [`<textarea>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) с сопутствующим им [`<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label),
```
Тут тоже не нужна запятая перед "с".

2020-10-23 10:43 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +- [`<audio>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) и [`<video>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)при наличии контролов,
```suggestion
- [`<audio>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) и [`<video>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) при наличии контролов,
```
Пропущен пробел после ссылки.

2020-10-23 11:14 UTC, TatianaFokina requested changes

2020-10-23 11:14 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Нет необходимости устанавливать `tabindex` интерактивным элементам, которые могут получать фокус с клавиатуры (например, `<button>`). Кроме того, вам не нужно прописывать `tabindex` неинтерактивным э
```suggestion
Нет необходимости устанавливать `tabindex` для интерактивных элементов, которые могут получать фокус с клавиатуры (например, `<button>`). Кроме того, вам не нужно прописывать `tabindex` неинтерактивным элементам, чтобы их могли прочесть вспомогательные устройства (на самом деле, отсутствие `role` и доступного имени является ошибкой с точки зрения WCAG). Это может привести к [нежелательному пользовательскому опыту](https://adrianroselli.com/2019/02/uncanny-a11y.html#Tabindex) у тех, кто использует вспомогательные устройства. У таких пользователей уже есть другие, ожидаемые ими способы чтения контента.
```

2020-10-23 11:14 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Иногда бывает необходимость запретить состояние фокуса. Хороший пример запрета — это [захват фокуса](https://hiddedevries.nl/en/blog/2017-01-29-using-javascript-to-trap-focus-in-an-element), временно
```suggestion
Иногда есть необходимость запретить состояние фокуса. Хороший пример запрета — это [ловушка фокуса](https://hiddedevries.nl/en/blog/2017-01-29-using-javascript-to-trap-focus-in-an-element), которая временно ограничивает событие фокуса у родительского элемента и у его дочерних элементов.
```
Обычно я встречала перевод "ловушка фокуса" у этого термина. Мне он кажется более устоявшимся, чем "захват фокуса . Но могу ошибаться.

2020-10-23 11:14 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +## Захват фокуса
```suggestion
## Ловушка фокуса
```
Может лучше "ловушка фокуса"?

2020-10-23 12:15 UTC, vasiliy-dudin requested changes

2020-10-23 12:15 UTC, vasiliy-dudin commented on src/articles/focus-and-inert/index.md
> +Захват фокуса не стоит путать с ограничением [навигации с клавиатуры](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html). Ограничение навигации с клавиатуры является причино
```suggestion
Ловушку фокуса не стоит путать с [ловушкой клавиатуры)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html). Ловушки клавиатуры — это ситуации, когда невозможно закрыть виджет или перейти к другому компоненту из-за вложенного цикла плохо прописанной логики.
```

- Для консистентности заменяем "захват" фокуса на "ловушку".
- Нет явного противопоставления терминов, я бы использовал схожие названия. И, вроде бы, в русском нет, устоявшегося термина "ограничение навигации с клавиатуры".

2020-10-23 12:21 UTC, vasiliy-dudin requested changes

2020-10-23 12:21 UTC, vasiliy-dudin commented on src/articles/focus-and-inert/index.md
> +Примером ситуации, когда необхдимо захватить фокус, может быть появление модального окна.
```suggestion
Практический пример того, как вы могли бы использовать ловушку фокуса — это модальное окно:
```
Проще и ближе к переводу.

2020-10-23 12:38 UTC, vasiliy-dudin commented on src/articles/focus-and-inert/index.md
> +6. Уйти с захваченной области;
Не забыть изменить "захват" на "ловушку".

2020-10-23 13:57 UTC, TatianaFokina requested changes

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +2. Определить границы захваченного контента (например, модального окна), включая первый и последний фокусируемый элемент;
```suggestion
2. Определить границы содержимого ловушки фокуса (например, модального окна), включая первый и последний фокусируемый элемент;
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +3. Убрать как интерактивность, так и видимость всего, что может иметь фокус и находится вне рамок захваченного контента;
```suggestion
3. Убрать как интерактивность, так и видимость всего, что может иметь фокус и находится вне рамок содержимого ловушки фокуса;
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +4. Переместить фокус в захваченный контент;
```suggestion
4. Переместить фокус на содержимое ловушки фокуса;
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +6. Уйти с захваченной области;
```suggestion
6. Выйти из содержимого ловушки фокуса, когда сработает нужное событие;
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +8. Переместить фокус обратно на интерактивный элемент, вызвавший блокировку содержимого.
```suggestion
8. Переместить фокус обратно на интерактивный элемент, который вызвал ловушку фокуса.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Не стану врать: все эти действия отнимают много времени. Но всё же, управление фокусом и удобный порядок фокусировки являются частью [WCAG (руководства по доступности в вебе)](https://www.w3.org/TR/U
```suggestion
Не стану врать: все эти действия отнимают много времени. Но всё же, управление фокусом и удобный порядок фокусировки являются частью [WCAG (руководства по доступности в вебе)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html). Тема достаточна важна, чтобы считать её частью [международного правового стандарта о юзабилити](https://www.w3.org/WAI/policies/).
```
Кажется, что в данном случае уместнее не переводить и использовать "юзабилити", потому что юзабилити — более широкое понятие, чем просто удобство использования.

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +[Скринридеры обладают режимом взаимодействия](https://tink.uk/understanding-screen-reader-interaction-modes/), который позволяет им проходить по странице виртуальным курсором. А ещё виртуальный курсо
```suggestion
[У скринридеров есть режим взаимодействия](https://tink.uk/understanding-screen-reader-interaction-modes/), который позволяет им проходить по странице или просматривать её с помощью виртуального курсора. А ещё виртуальный курсор позволяет пользователю скринридера обнаруживать неинтерактивные части страницы (заголовки, списки и т.  д.). В отличие от использования Tab, виртуальный курсор доступен только пользователям скринридера.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Я намеренно избегаю использования `<dialog>`для модального окна из-за [многочисленных проблем с поддержкой](https://www.scottohara.me/blog/2019/03/05/open-dialog.html).
```suggestion
Я намеренно избегаю использования `<dialog>` для модального окна из-за [многочисленных проблем с поддержкой](https://www.scottohara.me/blog/2019/03/05/open-dialog.html).
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Фокус ограничен рамками модального окна. Когда мы закрываем его, мы убираем `inert` из `<main>`. Этот способ ограничения фокуса проще, чем другие методы.
```suggestion
Фокус ограничен рамками модального окна. Когда мы закрываем его, то убираем `inert` из `<main>`. Этот способ управления ловушкой фокуса проще, чем другие методы.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +**Помните:** событие закрытия модального окна может быть вызвано не только нажатием соответствующих кнопок, но и нажатием Esc. А ещё некоторые модальные окна могут быть закрыты по клику на оверлей.
```suggestion
**Помните:** событие закрытия модального окна может быть вызвано не только нажатием на кнопки внутри нашего модального окна из примера, но и при нажатии на Esc. А ещё некоторые модальные окна могут быть закрыты по клику на оверлей.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Все последние версии [Edge, Chrome и Opera поддерживают `inert`](https://caniuse.com/#feat=mdn-api_htmlelement_inert), если [включены экспериментальные функции веб-платформ](https://css-irl.info/how-
```suggestion
Все последние версии [Edge, Chrome и Opera поддерживают `inert`](https://caniuse.com/#feat=mdn-api_htmlelement_inert), если [включены экспериментальные функции веб-платформ](https://css-irl.info/how-to-enable-experimental-web-platform-features/). Также [скоро появится](https://bugzilla.mozilla.org/show_bug.cgi?id=1655722) его поддержка в Firefox! Единственное исключение — Safari, как мобильный, так и десктопный.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Мне бы очень хотелось, чтобы Apple реализовала встроенную поддержку `inert`. Хотя и [существует полифил](https://github.com/WICG/inert), у него [серьёзные проблемы с поддержкой скринридерами](https:/
```suggestion
Мне бы очень хотелось, чтобы Apple реализовала встроенную поддержку `inert`. Хоть [полифил и существует](https://github.com/WICG/inert), но у него [серьёзные проблемы с поддержкой скринридерами](https://www.scottohara.me/blog/2019/03/05/open-dialog.html#does-the-polyfill-help). Нехорошо!
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +> Полифил обойдётся вам дорого с точки зрения производительности в отличие от нативного `inert`, т. к. он требует изрядного количества перемещений по DOM.
```suggestion
> Полифил обойдётся вам дорого с точки зрения производительности, в отличие от нативного `inert`, т. к. он требует изрядного количества перемещений по DOM.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Для устройств с низким энергопотреблением, таких как [бюджетные Android смартфоны и устаревшие ноутбуки](https://www.pewresearch.org/fact-tank/2019/05/07/digital-divide-persists-even-as-lower-income-
```suggestion
Для устройств с низким энергопотреблением, таких как [бюджетные Android-смартфоны и устаревшие ноутбуки](https://www.pewresearch.org/fact-tank/2019/05/07/digital-divide-persists-even-as-lower-income-americans-make-gains-in-tech-adoption/ft\_17-03-21\_low-incometech_smartphone/), а также тех, что выполняют сложные задачи (например, запуск нескольких приложений сразу), это может привести к зависанию или сбоям. Нативная браузерная поддержка делает такие процессы менее затратными в этом плане, так как у браузера есть доступ ко всем частям DOM, в отличие от JS.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Лично я разочарован тем, что Apple не поддерживает `inert`. Хотя я понимаю, что добавление новых функций в браузер — невероятно сложная и трудная работа, `inert` кажется функцией, которую Apple могла
```suggestion
Лично я разочарован тем, что Apple не поддерживает `inert`. Хотя понимаю, что добавление новых функций в браузер — невероятно сложная и трудная работа. `inert` кажется функцией, которую Apple стоило бы начать поддерживать гораздо раньше.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +macOS и iOS всегда имели хорошую поддержку доступности, а поддержка вспомогательных технологий — важная часть [их маркетинговой кампании](https://www.apple.com/accessibility/). Поддержка `inert` пред
```suggestion
macOS и iOS всегда имели хорошую поддержку доступности, а поддержка вспомогательных технологий — важная часть [их маркетинговой кампании](https://www.apple.com/accessibility/). Поддержка `inert` представляется как естественное продолжение миссии Apple ввиду того, что сама эта функция смогла бы облегчить разработку доступных веб-интерфейсов в разы.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +К сожалению, Apple держит в тайне, когда появится поддержка этого атрибута. Поэтому поддержка `inert` — все еще открытый вопрос.
```suggestion
К сожалению, Apple держит в тайне, когда появится поддержка этого атрибута. Поэтому поддержка `inert` — всё ещё открытый вопрос.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +Управление фокусом требует навыка и осторожности. Но это того стоит. Атрибут `inert` облегчит это.
```suggestion
Управление фокусом требует некоторых навыков и осторожности, но это того стоит. Атрибут `inert` значительно облегчит эту задачу.
```

2020-10-23 13:57 UTC, TatianaFokina commented on src/articles/focus-and-inert/index.md
> +- [Using JavaScript to trap focus in an element](https://hiddedevries.nl/en/blog/2017-01-29-using-javascript-to-trap-focus-in-an-element) (Хидде де Врис)
```suggestion
- [Controlling focus with tabindex](https://youtu.be/Pe0Ce1WtnUM) (A11ycasts, эпизод 4).
- [Using the tabindex attribute](https://developer.paciellogroup.com/blog/2014/08/using-the-tabindex-attribute/) (The Paciello Group).
- [Using JavaScript to trap focus in an element](https://hiddedevries.nl/en/blog/2017-01-29-using-javascript-to-trap-focus-in-an-element) (Хидде де Врис).
```

2020-10-23 19:16 UTC, lex111 commented on src/articles/focus-and-inert/index.md
> +5. Слушать события, сигнализирующие об уходе с выделенной области (сохранение, отмена, нажатие Esc и так далее);
```suggestion
5. Обрабатывать события, сигнализирующие об уходе с выделенной области (сохранение, отмена, нажатие Esc и так далее);
```

2020-10-23 19:16 UTC, lex111 commented on src/articles/focus-and-inert/index.md
> +Перемещение по DOM подразумевает, что JavaSсript в полифиле требует высокой вычислительной мощности и, следовательно, в конечном итоге замедлит пользователя.
Русское "с"

```suggestion
Перемещение по DOM подразумевает, что JavaScript в полифиле требует высокой вычислительной мощности и, следовательно, в конечном итоге замедлит пользователя.
```

2020-10-25 22:49 UTC, vasiliy-dudin requested changes
Ещё раз перечитал. Это всё, что нашёл.

2020-10-25 22:49 UTC, vasiliy-dudin commented on src/articles/focus-and-inert/index.md
> +Нет необходимости устанавливать `tabindex` для интерактивных элементов, которые могут получать фокус с клавиатуры (например, `<button>`). Кроме того, вам не нужно прописывать `tabindex` неинтерактивн
Выглядит как атрибут role, а тут речь роли элемента.
Оригинал:
```(in fact, this is a WCAG failure if no role and accessible name is present)```
```suggestion
Нет необходимости устанавливать `tabindex` для интерактивных элементов, которые могут получать фокус с клавиатуры (например, `<button>`). Кроме того, вам не нужно прописывать `tabindex` неинтерактивным элементам, чтобы их могли прочесть вспомогательные устройства (на самом деле, отсутствие роли и доступного имени является ошибкой с точки зрения WCAG). На самом деле, это даже [усложняет навигацию](https://adrianroselli.com/2019/02/uncanny-a11y.html#Tabindex) для тех, кто использует вспомогательные устройства. У таких пользователей уже есть другие, ожидаемые ими способы чтения контента.
```

2020-10-25 22:49 UTC, vasiliy-dudin commented on src/articles/focus-and-inert/index.md
> +- У вас плохое зрение и дисплей с увеличением, при котором фокусировка за пределами модального окна может сбить с толку и дезориентировать;
"дисплей с увеличением" вызовет вопросы. Но не знаю, что это и как нормально перевести. В оригинале "magnified display".
Может речь про программную экранную лупу?

2020-10-25 22:49 UTC, vasiliy-dudin commented on src/articles/focus-and-inert/index.md
> +Не стану врать: все эти действия отнимают много времени. Но всё же, управление фокусом и удобный порядок фокусировки являются частью [WCAG (руководства по доступности в вебе)](https://www.w3.org/TR/U
Есть распространённый перевод названия гайда, я бы использовал его.
```suggestion
Не стану врать: все эти действия отнимают много времени. Но всё же, управление фокусом и удобный порядок фокусировки являются частью [WCAG (руководства по обеспечению доступности веб-контента)](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html). Тема достаточна важна, чтобы считать её частью [международного правового стандарта о юзабилити](https://www.w3.org/WAI/policies/).
```

2020-10-25 22:49 UTC, vasiliy-dudin commented on src/articles/focus-and-inert/index.md
> +Перемещение по DOM подразумевает, что JavaScript в полифиле требует высокой вычислительной мощности и, следовательно, в конечном итоге замедлит пользователя.
Чуть ближе к сути, сам пользователь не будет замедлен.
```suggestion
Перемещение по DOM подразумевает, что JavaScript в полифиле требует высокой вычислительной мощности и, следовательно, в конечном итоге замедлит использование.
```

2020-10-26 08:52 UTC, pepelsbey commented on src/articles/focus-and-inert/index.md
> +- У вас плохое зрение и дисплей с увеличением, при котором фокусировка за пределами модального окна может сбить с толку и дезориентировать;
```suggestion
- У вас плохое зрение и интерфейс увеличен с помощью экранной лупы, при которой фокусировка за пределами модального окна может сбить с толку и дезориентировать;
```

2020-10-26 09:38 UTC, merged

2020-10-26 09:49 UTC, pepelsbey commented
[Перевод вышел!](https://web-standards.ru/articles/focus-and-inert/) Всем спасибо :) И особенно @summertime-fms