Фикс карточки статей для маленьких экранов
web-standards-ru/web-standards.ru pull request #202
Opened 2021-02-11 06:20 UTC by kmisha

Если ширина экрана меньше 320px то переносим автора на новую строку.
Должно пофиксить #191 
![315px](https://user-images.githubusercontent.com/8425363/107607376-7f12f900-6c52-11eb-891a-eec56866eb65.png)

2021-04-07 04:41 UTC, monochromer commented
@kmisha  Длинные имена не помещаются на экран. Перестройку нужно делать явно на больших экранах, например, `>=460px`

![image](https://user-images.githubusercontent.com/6412192/113810886-9d91fe00-9784-11eb-9a40-13dc71b2d4b7.png)

Ну и [мое мнение](https://github.com/web-standards-ru/web-standards.ru/issues/191#issuecomment-806418835) - слишком много пустого пространства расходуется зря, из-за чего и возникают проблемы с переполнением.

2021-04-07 04:47 UTC, monochromer requested changes

2021-04-07 04:47 UTC, monochromer commented on src/styles/blocks/article-card.css
> +@media (min-width: 320px) {
Могут быть проблемы с переполнением. Лучше увеличить брейкпойнт, например `460px`

2021-04-08 12:58 UTC, kmisha commented on src/styles/blocks/article-card.css
> +@media (min-width: 320px) {
Да, давай так и сделаем

2021-04-08 13:47 UTC, monochromer approved these changes

2021-04-08 13:48 UTC, monochromer commented
Ок, Спасибо!

2021-04-08 13:48 UTC, merged