Добавляет статью о NJS
web-standards-ru/web-standards.ru pull request #253
Opened 2021-06-15 21:30 UTC by igsekor

Предлагаю статью о таком инструменте как NJS. Думаю, что это может быть интересно для фронтенд разработчиков, которые смогут теперь делать чуть больше на стороне сервера. Надеюсь, она сможет оказаться полезной... 😇🍀🙃

2021-06-16 10:10 UTC, MeFoDy reviewed
Интересная статья, прикольная идея подвязаться на вселенную ГП в заголовках.

2021-06-16 10:10 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +Теперь напишем наш собственный модуль — модуль, который будет шифровать данные 🙃. Возьмём самый простой способ шифрования и попробуем передавать и принимать данные с помощью него. Будем использовать
```suggestion
Теперь напишем наш собственный модуль — модуль, который будет шифровать данные 🙃. Возьмём самый простой способ шифрования и попробуем передавать и принимать данные с помощью него. Будем использовать очень простой [шифр Цезаря](https://ru.wikipedia.org/wiki/%D0%A8%D0%B8%D1%84%D1%80_%D0%A6%D0%B5%D0%B7%D0%B0%D1%80%D1%8F). Идея этого шифра заключается в том, чтобы каждый символ в сообщении заменять на другой, сдвинутый циклично на фиксированное число позиций в алфавите. Например, слово `JavaScript` будет преобразовано в слово `OfafXhwnuy` при смещении на пять символов.
```

2021-06-16 10:10 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +Попробуем сделать так, чтобы при приёме HTTP-запроса скрипт  возвращал расшифрованное / зашифрованное сообщение в зависимости от пути на сервере `/encode/` или `/decode/`.  Если мы обратимся к `/shif
```suggestion
Попробуем сделать так, чтобы при приёме HTTP-запроса скрипт возвращал расшифрованное / зашифрованное сообщение в зависимости от пути на сервере `/encode/` или `/decode/`.  Если мы обратимся к `/shift/`, то получим сдвиг, который заложен в нашу программу. Для обработки каждого пути напишем отдельные функции в модуле: `encode`, `decode`  и `shift`. С помощью функции `getMessage()` можно будет получить сообщения из переменных, переданных `GET` или `POST` запросом от клиента.
```

2021-06-16 10:10 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +var CAESAR_SHIFT = 5;
У читателя может возникнуть вопрос, почему не ES6-синтаксис. То ли я невнимательно читал, то ли выше нигде про это нет. ECMA262 описывает ES6.

2021-06-16 10:10 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +`r.return()` — отправляет тело HTTP-сообщения клиенту и статус ответа веб-сервера. `r.variables` хранит переменные, переданные в запросе клиента. Перед использованием нужно экспортировать необходимые
```suggestion
`r.return()` — отправляет тело HTTP-сообщения клиенту и статус ответа веб-сервера. `r.variables` хранит переменные, переданные в запросе клиента. Перед использованием нужно экспортировать необходимые функции в интерфейс, как это делается при работе с модулями в JavaScript.

Первая версия кода готова, теперь настроим веб-сервер.
```

2021-06-16 10:10 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +Установим Nginx и NJS. Для того чтобы ставить эксперименты было удобнее, установим окружение внутри Docker-контейнера.  Так можно будет работать с контейнером, как с удалённым сервером, а клиентом бу
```suggestion
Установим Nginx и NJS. Для того чтобы ставить эксперименты было удобнее, установим окружение внутри Docker-контейнера. Так можно будет работать с контейнером, как с удалённым сервером, а клиентом будет выступать наш компьютер. Вы можете сделать иначе, просто установив всё, что требуется, к себе на компьютер или на сервер. Подробнее о Docker можно почитать в цикле статей на Веб-стандартах «Распаковка Docker: ([часть 1](/articles/docker-unboxing-1/), [часть 2](/articles/docker-unboxing-2/), [часть 3](/articles/docker-unboxing-3/))».
```

2021-06-16 10:10 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +Обратите внимание на пути томов (`volumes`). В конфигурации используются связанные тома (`binded volumes`), то есть прямая ссылка на файловую систему компьютера, на котором запущен Docker. Однако ссы
```suggestion
Обратите внимание на пути томов (`volumes`). В конфигурации используются связанные тома (`binded volumes`), то есть прямая ссылка на файловую систему компьютера, на котором запущен Docker. Однако ссылки внутри контейнера очень важны. Конфигурацию и скрипт нужно поместить в `/etc/nginx/` и `/etc/nginx/njs/` соотвественно. В конфигурации дополнительно используется директива `js_path`, чтобы точно ничего не потерялось.
```

2021-06-16 10:10 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +Теперь можно посмотреть в браузере результат нашей работы по адресу `http://localhost`. Для того чтобы остановить веб-сервер, можно использовать сочетание клавиш \<kbd\>Ctrl C\</kbd\> или соответству
```suggestion
Теперь можно посмотреть в браузере результат нашей работы по адресу `http://localhost`. Для того чтобы остановить веб-сервер, можно использовать сочетание клавиш <kbd>Ctrl C</kbd> или соответствующий сигнал в Unix-подобных системах.
```

2021-06-16 10:12 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +    src: images/cover.png
А картинки нет пока? Или не будет?

2021-06-16 10:12 UTC, igsekor commented on src/articles/magic-njs/index.md
> +    src: images/cover.png
Я не стал делать пока, могу нарисовать что-то :)

2021-06-16 10:16 UTC, igsekor commented on src/articles/magic-njs/index.md
> +var CAESAR_SHIFT = 5;
Вот нельзя, к сожалению. Не пропускает NJS `let` и `const`.

2021-06-16 10:23 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +var CAESAR_SHIFT = 5;
Тогда хочу про это в статье, полезные знания, чтобы не дебажить потом «рабочий», но не работающий код :)

2021-06-16 10:27 UTC, MeFoDy commented on src/articles/magic-njs/index.md
> +    src: images/cover.png
Может, и не нужно. Просто сейчас на страничке статьи есть запрос, который сломанный. Смело убирай, статья вполне себе норм без всяких картинок.

2021-06-16 10:37 UTC, MeFoDy approved these changes
Хочу:
- Пояснений «очевидностей»
- Каких-то ссылок на статистику, где в тексте есть «лучше», «быстрее» — пруфы всегда надёжнее слов автора
- В список редакторов :)

В остальном даю ок, хорошая статья.

2021-06-16 10:50 UTC, igsekor commented
> Хочу

Пожалуйста 🙃

2021-06-16 20:54 UTC, amel-true commented
> Архитектура Nginx построена таким образом, чтобы выдерживать колоссальное количество запросов от несметного количества клиентов.

На самом деле не сильно-то отличается от event-loop в node.js :)

2021-06-16 21:13 UTC, amel-true requested changes
Спасибо, что поднимаешь такие темы! Нужно больше DevOps-практик :)
Отметил несколько спорных моментов.

2021-06-16 21:13 UTC, amel-true commented on src/articles/magic-njs/index.md
> +NJS — очень интересный инструмент. У команды была возможность использовать готовые решения, например, движки V8 или SpiderMonkey, но нет. Эти решения заточены в основном под браузеры, у них много все
> Эти решения заточены в основном под браузеры

Не так, эти движки прекрасно работают и вне браузера

> у них много всего лишнего и есть очевидные проблемы с производительностью.

Стоит избегать слово «очевидно». Проблема в том, что nginx использует js иначе — ближе к лямбдам. Маленький код, который запускается заново на каждый запрос. В этом случае действительно не нужен JIT и нужна возможность прекомпиляции.

2021-06-16 21:13 UTC, amel-true commented on src/articles/magic-njs/index.md
> +Начнём с классического «Hello world!». Логика работы скрипта заключается в том, чтобы прослушивать заранее заданный порт, например 8080, и при обращении к корневой папке сайта отослать клиенту ответ
Английский текст заключается в лапки — "Hello world!"

2021-06-16 21:13 UTC, amel-true commented on src/articles/magic-njs/index.md
> +`njs` — это подмножество JavaScript. Что можно, а что нельзя, определено [дорожной картой](http://nginx.org/ru/docs/njs/compatibility.html). `njs` поддерживает стандарт [ECMA-262](http://www.ecma-int
> `njs` — это подмножество JavaScript.
Может быть корректней «работает с ограниченным подмножеством js» ?

2021-06-17 10:15 UTC, igsekor commented on src/articles/magic-njs/index.md
> +NJS — очень интересный инструмент. У команды была возможность использовать готовые решения, например, движки V8 или SpiderMonkey, но нет. Эти решения заточены в основном под браузеры, у них много все
Согласен @amel-true. Поправил 😇

2021-06-17 10:18 UTC, igsekor commented on src/articles/magic-njs/index.md
> +`njs` — это подмножество JavaScript. Что можно, а что нельзя, определено [дорожной картой](http://nginx.org/ru/docs/njs/compatibility.html). `njs` поддерживает стандарт [ECMA-262](http://www.ecma-int
Я не хотел противоречить [официальной документации](http://nginx.org/en/docs/njs/index.html). Они позиционируют njs как диалект JS, насколько я понимаю.

2021-06-17 11:26 UTC, amel-true approved these changes

2021-06-17 13:53 UTC, merged

2021-06-17 13:53 UTC, pepelsbey commented
Спасибо всем!