Фикс шапки при масштабировании и разрешении 735px
web-standards-ru/web-standards.ru pull request #271
Opened 2021-07-07 05:22 UTC by TakNePoidet

#270

2021-07-07 08:17 UTC, pepelsbey requested changes
Не стоит коммитить нерелевантные для пулреквеста правки:

- .gitignore
- package-lock.json

2021-07-07 08:18 UTC, pepelsbey commented
В остальном — спасибо :) И жаль, что приходится менять принцип вёрстки из-за такого бага. Проверю локально и посмотрим, насколько хорошо получилось.

2021-07-07 13:58 UTC, TakNePoidet commented
Убрал лишние. 

Почему это считается другим принципом верстки, в проекте же `Mobile-first` и это больше похоже на него?

2021-07-09 06:40 UTC, monochromer commented
> Почему это считается другим принципом верстки, в проекте же `Mobile-first` и это больше похоже на него?

В проекте скорее используется подход Generic First (Common First), когда пишутся общие стили для всех экранов, а затем меняются состояния при помощи `min-width` и `max-width`.

Тут объясняется суть подхода:
- [Адаптивная шапка с выпадающим меню на гридах, часть 1](https://www.youtube.com/watch?v=o7A0e4PkSAQ)
- [Адаптивная шапка с выпадающим меню на гридах, часть 2](https://www.youtube.com/watch?v=0_v36dyI3kI)
- [Alastair Hodgson. Generic First CSS: New Thinking On Mobile First](https://www.smashingmagazine.com/2018/12/generic-css-mobile-first/)

Возможно, стоит просто заменить `(max-width: 735px)` на `(not all and (min-width: 736px))`. Последнее работает как "отрицание" первого.

2021-07-09 12:52 UTC, pepelsbey commented
> Generic First (Common First)

Ого, я не знал, что у этого подхода есть название :)

2021-07-09 18:32 UTC, monochromer commented
> Возможно, стоит просто заменить (max-width: 735px) на (not all and (min-width: 736px)). Последнее работает как "отрицание" первого.

Проверил - вроде работает

2021-07-09 18:50 UTC, TakNePoidet commented
> Проверил - вроде работает

У меня не сработало при масштабе
![image](https://user-images.githubusercontent.com/23022574/125123650-5d8a4080-e110-11eb-91da-a81e8d1962d5.png)

2021-07-09 19:21 UTC, monochromer commented
Может, ошибаюсь, но на скрине прод или локальное окружение?

2021-07-09 19:26 UTC, TakNePoidet commented
Локальное

2021-07-11 16:14 UTC, monochromer commented
Ещё предлагаю проверить такой вариант. В Bootstrap решали подобную проблему с использованием дробных значений, например, `(max-width: 599.98px)` там, где нужно было `(max-width: 599px)`. 

Но чтобы этот хак был чуть красивее, можно использовать calc - `(max-width: calc(736px - 0.02px))`. Calc работает во [всех современных браузерах](https://stackoverflow.com/a/23675934/8171946).

2024-08-15 12:45 UTC, pepelsbey commented
Исправили в другом месте, сейчас не ломается.

2024-08-15 12:45 UTC, closed without merging