Добавляет обработку timecode из url
web-standards-ru/web-standards.ru pull request #300
Opened 2022-02-16 08:21 UTC by vanyauhalin

2022-02-16 09:05 UTC, pepelsbey requested changes
Круто! Я бы чуть-чуть дожал :) Накидал идей:

- Было бы здорово понимать, что 01:01 это тоже самое, что 00:01:01, [я что-то такое делал уже](https://github.com/lp-cast/3lp.11ty/blob/main/src/scripts/scripts.js#L4-L16)
- К сожалению, всё срабатывает только при загрузке страницы, руками таймкод не подобрать: приходится его вводить и перезагружать страницу, чтобы проверить. Думаю, можно слушать изменения якоря, и перематывать плеер.
- Ещё ожидаешь от кнопок с таймкодами, что они не только будут переключать плеер, но и менять якорь в адресе. Это поможет людям находить эту фичу.

2022-02-16 10:49 UTC, vanyauhalin commented
> Круто! Я бы чуть-чуть дожал :) Накидал идей:
> 
> * Было бы здорово понимать, что 01:01 это тоже самое, что 00:01:01, [я что-то такое делал уже](https://github.com/lp-cast/3lp.11ty/blob/main/src/scripts/scripts.js#L4-L16)
> * К сожалению, всё срабатывает только при загрузке страницы, руками таймкод не подобрать: приходится его вводить и перезагружать страницу, чтобы проверить. Думаю, можно слушать изменения якоря, и перематывать плеер.
> * Ещё ожидаешь от кнопок с таймкодами, что они не только будут переключать плеер, но и менять якорь в адресе. Это поможет людям находить эту фичу.

Отличные замечания. Всё добавил, всё поправил.

2022-03-01 15:12 UTC, pepelsbey approved these changes

2022-03-01 15:14 UTC, merged

2022-03-01 15:14 UTC, pepelsbey commented
Спасибо!